<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CreateEmployees</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-03-21T10:36:22</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>52a254f8-44e6-4826-b576-7f140ead840a</testSuiteGuid>
   <testCaseLink>
      <guid>bb5369cf-5b32-4c83-a627-be85a688c29b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PIM/CreateEmployee</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4b543ecd-ef18-40e5-a733-73f5b856f1c1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Employees</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4b543ecd-ef18-40e5-a733-73f5b856f1c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>employeeFirstName</value>
         <variableId>58d56dae-bb72-4c49-a445-b1e21ec502fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4b543ecd-ef18-40e5-a733-73f5b856f1c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>employeeLastName</value>
         <variableId>de158f68-bd90-4da8-b6d4-4bf1a153f282</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
